openapi: 3.0.0
info:
  title: Profiles Controller Schema
  version: 1.0.0

paths:
  /profiles:
    # get:
    #   operationId: fetchAllTodos
    #   description: ログインユーザのTODOを全て取得
    #   parameters: []
    #   responses:
    #     '200':
    #       description: TODO一覧の取得完了
    #       content:
    #         application/json:
    #           schema:
    #             $ref: '#/components/schemas/FetchAllTodosResponseDto'
    #     '400':
    #       $ref: '../errors.yml#responses/400'
    #     '401':
    #       $ref: '../errors.yml#responses/401'
    post:
      operationId: createProfile
      description: ログインユーザのプロフィールを更新
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileDto'
      responses:
        '201':
          description: プロフィールの更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateProfileResponseDto'
        '400':
          $ref: '../errors.yml#responses/400'
        '401':
          $ref: '../errors.yml#responses/401'
    get:
      operationId: fetchProfileForEdit
      description: 編集対象となるログインユーザのプロフィールを取得
      parameters: []
      responses:
        '200':
          description: プロフィールの取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileForEditDto'
        '400':
          $ref: '../errors.yml#responses/400'
        '401':
          $ref: '../errors.yml#responses/401'
        '404':
          $ref: '../errors.yml#responses/404'
    # put:
    #   operationId: updateTodo
    #   description: ログインユーザのTODOの更新
    #   parameters:
    #     - name: id
    #       required: true
    #       in: path
    #       schema:
    #         type: string
    #   requestBody:
    #     required: true
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/components/schemas/UpdateTodoDto'
    #   responses:
    #     '200':
    #       description: TODOの更新成功
    #       content:
    #         application/json:
    #           schema:
    #             $ref: '#/components/schemas/UpdateTodoResponseDto'
    #     '400':
    #       $ref: '../errors.yml#responses/400'
    #     '401':
    #       $ref: '../errors.yml#responses/401'
    #     '404':
    #       $ref: '../errors.yml#responses/404'
    # delete:
    #   operationId: deleteTodo
    #   description: ログインユーザのTODOの削除
    #   parameters:
    #     - name: id
    #       required: true
    #       in: path
    #       schema:
    #         type: string
    #   responses:
    #     '200':
    #       description: TODOの削除成功
    #       content:
    #         application/json:
    #           schema:
    #             $ref: '#/components/schemas/DeleteTodoResponseDto'
    #     '400':
    #       $ref: '../errors.yml#responses/400'
    #     '401':
    #       $ref: '../errors.yml#responses/401'
    #     '404':
    #       $ref: '../errors.yml#responses/404'

components:
  schemas:
    # FetchAllTodosResponseDto:
    #   $ref: './components/fetch_all_todos_response.dto.yml'
    ProfileForEditDto:
      $ref: './components/profile_for_edit.dto.yml'
    UpdateProfileDto:
      $ref: './components/update_profile.dto.yml'
    UpdateProfileResponseDto:
      $ref: './components/update_profile_response.dto.yml'
    # UpdateTodoDto:
    #   $ref: './components/update_todo.dto.yml'
    # UpdateTodoResponseDto:
    #   $ref: './components/update_todo_response.dto.yml'
    # DeleteTodoResponseDto:
    #   $ref: './components/delete_todo_response.dto.yml'
